name: "Deploy Frontend"
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  FRONTEND_APP_NAME: "gitops-frontend"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Frontend Repository"
        uses: "actions/checkout@v4"

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build and Push Frontend"
        run: |-
          IMAGE_TAG="${GITHUB_REF#refs/*/}"
          FRONTEND_IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/gitops-frontend:${IMAGE_TAG}"
          docker build -f Dockerfile -t "${FRONTEND_IMAGE_NAME}" .
          docker push "${FRONTEND_IMAGE_NAME}"
